# Generated by Django 3.2.5 on 2021-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
