# Generated by Django 3.2.5 on 2021-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wallet_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_final_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ انقضای token'),
        ),
    ]
